apiVersion: v1
kind: Secret
metadata:
  name: "fluree-secrets"
type: Opaque
data:
  {{- if .Values.config.fdbGroupPrivateKey }}
  fdbGroupPrivateKey: {{ .Values.config.fdbGroupPrivateKey | b64enc }}
  {{- end }}
  {{- if .Values.config.fdbEncryptionSecret }}
  fdbEncryptionSecret: {{ .Values.config.fdbEncryptionSecret | b64enc}}
  {{- end }}
